function handles = scannerGUI_fig
% Build a GUI for the scanner and return the handles to the plot and ui objects
%	
% function handles = scannerGUI_fig
%
%
% Inputs
%  None
%
% Outputs
%  handles - a structure of handles associated with the UI elements in the GUI
%
% Rob Campbell - Basel 2016
%
%
% Also see:
% scannerGUI, scanAndAcquire_OO




handles.hFig = figure;
set(handles.hFig, ...
	'ToolBar', 'none', ...
	'MenuBar', 'none', ...
	'Name', 'scannerGUI',...
    'Resize', 'Off');
handles.hFig.Position(3)=500;
handles.hFig.Position(4)=160;



% - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
%Scan button
handles.startStopScan = uicontrol(...
    'Parent', handles.hFig, ...
    'Units', 'pixels', ...
    'FontSize', 10, ...
    'FontWeight', 'Bold', ...
    'Position', [12 95  120  55], ...
    'ForeGroundColor','g', ...
    'String', 'START SCAN',...
    'HandleVisibility','Off');


% - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
%Status bar along the bottom of the window
handles.statusBar = uicontrol(...
    'Parent', handles.hFig, ...
    'Units', 'pixels', ...
    'FontSize', 10, ...
    'FontWeight', 'Bold', ...
    'Style','Text', ...
    'Position', [1 1  500  18], ...
    'BackgroundColor',[1,1,1]*0.75, ...
    'HorizontalAlignment', 'left', ...
    'String', '',...
    'HandleVisibility','Off');


% - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
%Bidi checkbox and phase delay
handles.bidiFrame = uipanel(...
    'Parent', handles.hFig, ...
    'Units', 'pixels', ...
    'FontSize', 10, ...
    'FontWeight', 'Bold', ...
    'Position', [142 90  110  64], ...
    'Title', 'Bidi scan',...
    'HandleVisibility','Off');

    handles.bidi = uicontrol(...
        'Parent', handles.bidiFrame, ... %Note: nested within the bidiFrame
        'Units', 'pixels', ...
        'FontSize', 10, ...
        'FontWeight', 'Bold', ...
        'Position', [4 24  100   20], ...
        'Style','CheckBox', ...
        'String', 'Enable Bidi');

    %Phase delay for bidi 
    handles.bidiPhase = uicontrol(...
        'Parent', handles.bidiFrame, ...
        'Units', 'pixels', ...
        'FontSize', 10, ...
        'FontWeight', 'Bold', ...
        'Position', [4 4 59 20], ...
        'Style','Edit', ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor',[1,1,1]*0.75, ...
        'String', '',...
        'HandleVisibility','Off');



% - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
%Save fname
handles.saveFrame = uipanel(...
    'Parent', handles.hFig, ...
    'Units', 'pixels', ...
    'FontSize', 10, ...
    'FontWeight', 'Bold', ...
    'Position', [258 90  240 64], ...
    'Title', 'Save to TIFF',...
    'HandleVisibility','Off');

    handles.save = uicontrol(...
        'Parent', handles.saveFrame, ... %Note: nested within the saveFrame
        'Units', 'pixels', ...
        'FontSize', 10, ...
        'FontWeight', 'Bold', ...
        'Position', [4 24  120   20], ...
        'Style','CheckBox', ...
        'String', 'Save',...
        'HandleVisibility','Off');

    %file name to save to
    handles.saveFname = uicontrol(...
        'Parent', handles.saveFrame, ...
        'Units', 'pixels', ...
        'FontSize', 10, ...
        'FontWeight', 'Bold', ...
        'Position', [4 4, 225 20], ...
        'Style','Edit', ...
    	'HorizontalAlignment', 'left', ...
        'BackgroundColor',[1,1,1]*0.75, ...
        'String', '',...
        'HandleVisibility','Off');




% - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
%Image
handles.image = uipanel(...
    'Parent', handles.hFig, ...
    'Units', 'pixels', ...
    'FontSize', 10, ...
    'FontWeight', 'Bold', ...
    'Position', [10 22  385 64], ...
    'Title', 'Image',...
    'HandleVisibility','Off');

    handles.invert = uicontrol(...
        'Parent', handles.image, ... 
        'Units', 'pixels', ...
        'FontSize', 10, ...
        'FontWeight', 'Bold', ...
        'Position', [325 31  120   20], ...
        'Style','CheckBox', ...
        'String', 'invert',...
        'HandleVisibility','Off');


    handles.fillFractionLabel = uicontrol(...
        'Parent', handles.image, ...
        'Units', 'pixels', ...
        'FontSize', 10, ...
        'FontWeight', 'Bold', ...
        'Position', [4 6, 75 16], ...
        'Style','Text', ...
        'HorizontalAlignment', 'left', ...
        'String', 'fill-fraction',...
        'HandleVisibility','Off');
    handles.fillFraction = uicontrol(...
        'Parent', handles.image, ...
        'Units', 'pixels', ...
        'FontSize', 10, ...
        'FontWeight', 'Bold', ...
        'Position', [65 6, 30 20], ...
        'Style','Edit', ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor',[1,1,1]*0.75, ...
        'String', '',...
        'HandleVisibility','Off');


    handles.scannerAmpLabel = uicontrol(...
        'Parent', handles.image, ...
        'Units', 'pixels', ...
        'FontSize', 10, ...
        'FontWeight', 'Bold', ...
        'Position', [4 32, 75 16], ...
        'Style','Text', ...
        'HorizontalAlignment', 'left', ...
        'String', 'scan amp',...
        'HandleVisibility','Off');
    handles.scannerAmp = uicontrol(...
        'Parent', handles.image, ...
        'Units', 'pixels', ...
        'FontSize', 10, ...
        'FontWeight', 'Bold', ...
        'Position', [65 30, 30 20], ...
        'Style','Edit', ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor',[1,1,1]*0.75, ...
        'String', '',...
        'HandleVisibility','Off');


    handles.samplesPixLabel = uicontrol(...
        'Parent', handles.image, ...
        'Units', 'pixels', ...
        'FontSize', 10, ...
        'FontWeight', 'Bold', ...
        'Position', [115 6, 75 16], ...
        'Style','Text', ...
        'HorizontalAlignment', 'left', ...
        'String', 'samples/pix',...
        'HandleVisibility','Off');
    handles.samplesPix = uicontrol(...
        'Parent', handles.image, ...
        'Units', 'pixels', ...
        'FontSize', 10, ...
        'FontWeight', 'Bold', ...
        'Position', [185 6, 30 20], ...
        'Style','Edit', ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor',[1,1,1]*0.75, ...
        'String', '',...
        'HandleVisibility','Off');


    handles.imSizeLabel = uicontrol(...
        'Parent', handles.image, ...
        'Units', 'pixels', ...
        'FontSize', 10, ...
        'FontWeight', 'Bold', ...
        'Position', [115 32, 75 16], ...
        'Style','Text', ...
        'HorizontalAlignment', 'left', ...
        'String', 'image size',...
        'HandleVisibility','Off');
    handles.imSize = uicontrol(...
        'Parent', handles.image, ...
        'Units', 'pixels', ...
        'FontSize', 10, ...
        'FontWeight', 'Bold', ...
        'Position', [185, 30, 30 20], ...
        'Style','Edit', ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor',[1,1,1]*0.75, ...
        'String', '',...
        'HandleVisibility','Off');


    handles.sampRateLabel = uicontrol(...
        'Parent', handles.image, ...
        'Units', 'pixels', ...
        'FontSize', 10, ...
        'FontWeight', 'Bold', ...
        'Position', [230 6, 75 16], ...
        'Style','Text', ...
        'HorizontalAlignment', 'left', ...
        'String', 'sample rate',...
        'HandleVisibility','Off');
    handles.sampRate = uicontrol(...
        'Parent', handles.image, ...
        'Units', 'pixels', ...
        'FontSize', 10, ...
        'FontWeight', 'Bold', ...
        'Position', [295 6, 60 20], ...
        'Style','Edit', ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor',[1,1,1]*0.75, ...
        'String', '',...
        'HandleVisibility','Off');


    handles.AIrangeLabel = uicontrol(...
        'Parent', handles.image, ...
        'Units', 'pixels', ...
        'FontSize', 10, ...
        'FontWeight', 'Bold', ...
        'Position', [230 32, 75 16], ...
        'Style','Text', ...
        'HorizontalAlignment', 'left', ...
        'String', 'AI range',...
        'HandleVisibility','Off');
    handles.AIrange = uicontrol(...
        'Parent', handles.image, ...
        'Units', 'pixels', ...
        'FontSize', 10, ...
        'FontWeight', 'Bold', ...
        'Position', [285 30, 30 20], ...
        'Style','Edit', ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor',[1,1,1]*0.75, ...
        'String', '',...
        'HandleVisibility','Off');

% - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
%Image

handles.channels = uipanel(...
    'Parent', handles.hFig, ...
    'Units', 'pixels', ...
    'FontSize', 10, ...
    'FontWeight', 'Bold', ...
    'Position', [397 22  100 64], ...
    'Title', 'Channels',...
    'HandleVisibility','Off');

    handles.ai0 = uicontrol(...
        'Parent', handles.channels, ... 
        'Units', 'pixels', ...
        'FontSize', 10, ...
        'FontWeight', 'Bold', ...
        'Position', [4 30  40   20], ...
        'Style','CheckBox', ...
        'String', 'AI0',...
        'HandleVisibility','Off');

    handles.ai1 = uicontrol(...
        'Parent', handles.channels, ... 
        'Units', 'pixels', ...
        'FontSize', 10, ...
        'FontWeight', 'Bold', ...
        'Position', [46 30  40   20], ...
        'Style','CheckBox', ...
        'String', 'AI1',...
        'HandleVisibility','Off');

    handles.ai2 = uicontrol(...
        'Parent', handles.channels, ... 
        'Units', 'pixels', ...
        'FontSize', 10, ...
        'FontWeight', 'Bold', ...
        'Position', [4 4  40   20], ...
        'Style','CheckBox', ...
        'String', 'AI2',...
        'HandleVisibility','Off');

    handles.ai3 = uicontrol(...
        'Parent', handles.channels, ... 
        'Units', 'pixels', ...
        'FontSize', 10, ...
        'FontWeight', 'Bold', ...
        'Position', [46 4  40   20], ...
        'Style','CheckBox', ...
        'String', 'AI3',...
        'HandleVisibility','Off');
